### ISSUE TITLE
Automatically name monster tokens +1

### ISSUE THREAD

**Issue by orffen** [orffen/basicfantasyrpg#19]
For example, if I drop a Goblin token onto a scene, it should automatically be named "Goblin 1". When I drop another, it would be "Goblin 2". If I have 12 Goblins on the scene already, the next token dropped would be "Goblin 13".

**Comment by revwez** [comment]
The token mold module will do this, it just won't auto roll hit points if the system is set up to work with it. But the naming is done. I use it on sandbox all the time.

**Comment by orffen** [comment]
Thanks for the heads-up! I had this working on an uncommitted version of the code, but I can't remember how I looped through the already-active tokens. Will take a look at how Token Mold does it.
