### ISSUE TITLE
actorLink Token Defaults Actors

### ISSUE THREAD

**Issue by Stew-rt** [orffen/basicfantasyrpg#23]
Currently the default token option for "Link Actor Data" (actorLink) is unticked.

As it is, we can drag an arbitrary amount of monsters into a scene and update their hit points without updating the actor, I also noticed you've added a super-cool feature that generates their hit points.. This is great.. because we might need to quickly drag in 5 skeletons (and not have to copy 5 actors to achieve this)

I believe this is correct for Monsters, but it may make sense to have character tokens default to have this on, as they are more likely to persist between scenes.

Alternatively, as i'm building this compendium, I can specify the token configuration for all the monsters i'm adding.. have all of those default to actorLink: false - and the core module changes it's default to actorLink: true - this might be more in line with what people expect when using the system..

I dunno, what do you think?

**Comment by orffen** [comment]
Thanks Stew, I wasn't familiar with that option. Can you share any more detail about that? I can make the hit dice roller dependent on actorLink - if it's true, we don't want to re-roll character token hit points every time they're placed :)

I think the default behaviour should be to roll hit dice unless a monster has something specified not to do that.

**Comment by Stew-rt** [comment]
I've recorded a quick gif to explain myself.
So I create a new actor, it's Prototype Token defaults to Link Actor Data: False
Drag the actor to the scene twice, update each token's hit points differently, and it doesn't update the main actor sheet.
Then I modify the actor's Prototype Token to Link Actor Data: True, drag this actor to the scene. then when i update the token's hit points, it also update's the actor's sheet.
![Peek 2022-03-03 17-36](https://user-images.githubusercontent.com/40280034/156620863-334610fd-2e51-484c-97ce-e9e03190bf02.gif)

**Comment by orffen** [comment]
Thanks for this - I'll have a look for how we can set actorData: true for character sheets tokens.

**Comment by orffen** [comment]
Closed in 5aa0b18 for new character sheets.
