### ISSUE TITLE
Monster sheet attacks - what is the best approach?

### ISSUE THREAD

**Issue by Stew-rt** [orffen/basicfantasyrpg#24]
Adding (more complicated) attacks to a monster sheet has me a bit flummoxed.
For example, a Wyvern has the following stat block:
No. of Attacks: 1 bite/1 stinger or 2 talons/1 stinger
Damage: 2d8/1d6 + poison or 1d10/1d10/1d6 + poison

So the monster has the option of:
Attack with 1 bite AND 1 stinger
OR
1 talon AND 1 talon  AND 1 stinger

I've got two things i'm a little confused at how to represent in the sheet.

1st problem:
I can't really do as you have done with your example photo on the foundry forum,
and add a weapon called "2 talons" - because if one misses, and I roll for damage, it will roll damage as-if both hit.

So now i'm in a situation where I have (at least) 3 weapons:
Bite
Stinger
(Left )Talon
(Right Talon)

But now i'm not sure how to communicate the attack option to the DM that's just opened up this sheet....

2nd problem:
The + poison bit.. The only way I can think to do this, is a bit hacky, but if i name the Stinger attack, "Stinger (+poison)" - at least it comes up in the chat as: "Roll: Stinger (+poison) damage"

I was just wondering if you had a better solution for this.

**Comment by Stew-rt** [comment]
I wonder whether it'd be better to:
1) go with the "digital version of the paper sheet" approach, and have additional text boxes for at least "No. of Attacks" and maybe also "Damage" on Monster sheets..
2) go for some crazy automation, and have an "attack" object, which could be a sequence of weapon.attack functions (or whatever that is called in foundry)

**Comment by orffen** [comment]
I think both of these are overly complicated.

We’ve got a description tab where we can note unusual attack combinations.

I would add the attacks - remember “2 claws” is just a label. It can indicate to the GM that this attack can be used twice a turn.

Or, just add Claw, Claw, Bite - then each entry can be used once. Or Claw 1, Claw 2, Bite.

And again if the GM needs to make a choice about anything a bit more complex, just note it in the description.

Thanks,
Steve

On 5 Mar 2022, at 04:34, Stewart Webb ***@***.***> wrote:

﻿

I wonder whether it'd be better to:

  1.  go with the "digital version of the paper sheet" approach, and have additional text boxes for at least "No. of Attacks" and maybe also "Damage" on Monster sheets..
  2.  go for some crazy automation, and have an "attack" object, which could be a sequence of weapon.attack functions (or whatever that is called in foundry)

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Forffen%2Fbasicfantasyrpg%2Fissues%2F24%23issuecomment-1059417714&data=04%7C01%7C%7Cd7bf435f39e44bbf962708d9fe0daaa5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820156924390069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Dqk9h6JzbR8oNlj1Fd0qL%2BsLMBMty0vvzvrbJnDm0l4%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAQ7OQNEQ4HI5HL6D7EC5CDU6JJUTANCNFSM5P6IMCBQ&data=04%7C01%7C%7Cd7bf435f39e44bbf962708d9fe0daaa5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820156924390069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1C3r4i8wQRUp%2BUJkVy9sqEcmsnF3JgNw2d%2Fi723Q0nc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cd7bf435f39e44bbf962708d9fe0daaa5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820156924390069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yItA3RSKvjBtTZ1OlXHFZ4QQdXFH02f3N%2Fw0CqpHuwI%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cd7bf435f39e44bbf962708d9fe0daaa5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820156924390069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7jjO9uKnepAria2Y5I8o8dHkBmUWWwpneBcN8mbWXRU%3D&reserved=0>.

**Comment by orffen** [comment]
I added some more commentary here: https://github.com/orffen/basicfantasyrpg/pull/25#issuecomment-1079575787
