### ISSUE TITLE
Monster XP Calculation stops working at 25HD

### ISSUE THREAD

**Issue by totallybanjaxed** [orffen/basicfantasyrpg#36]
Monsters with HD over 25 don't get their XP calculated automatically.  Would it be possible to add that in?  The table in the SRD only goes up to 25 but then says: 

_"For monsters with more than 25 hit dice, add 750 XP to the XP Value and 25 XP to the Special Ability Bonus per additional hit die."_

Not sure how easy that is?  Maybe if the HD is above 25, you might be able to multiply the difference by 750XP and add it.  Or something.. I haven't a notion what I'm talking about here :)

However I am enjoying getting started with this game and your great module!  Cheers for all your work on it so far, it's great!

**Comment by orffen** [comment]
Thanks for the kind words! I'll take a look, it should be straightforward enough to add.

**Comment by orffen** [comment]
SRD details: https://www.basicfantasy.org/srd/#character_advancement

`_prepareMonsterData(actorData)` needs to be updated to check if there are more than 25 HD. Not too difficult, I'll include this in the next release, hopefully sometime next week.
