### ISSUE TITLE
XP calculation issue when HD includes negative modifier

### ISSUE THREAD

**Issue by totallybanjaxed** [orffen/basicfantasyrpg#37]
Hey, just another small XP bug I've noticed.  When a monster has a negative modifier to their HD, the XP is not being calculated correctly (the modifier should not change the XP total, only the main HD number should).

e.g.
![image](https://user-images.githubusercontent.com/31042157/192168567-77eaa053-cc39-47ee-b79c-c836e553af20.png)

If I recreate this then it calculates as 10 XP instead of 145 XP e.g.
![image](https://user-images.githubusercontent.com/31042157/192168640-b93ece45-aa84-4e0b-898f-d018dfb0c876.png)

If I remove the negative modifier then it calculates it correctly, e.g. 
![image](https://user-images.githubusercontent.com/31042157/192168664-f4a7b16c-7593-4103-9acf-b894fc26e096.png)

**Comment by orffen** [comment]
`data.xp.value = function () {` in `_prepareMonsterData(actorData)`
